name: test

on:
  workflow_dispatch:

jobs:
  build:
    # Apuntamos al runner de 8 núcleos con Ubuntu 22.04
    runs-on: depot-ubuntu-22.04
    
    steps:
    - name: Limpieza Agresiva
      run: |
        echo "Espacio disponible ANTES de la limpieza:"
        df -h
